import type { App, Plugin } from 'vue'
import {
  MyAffix,
  MyAlert,
  MyAnchor,
  MyAside,
  MyAutocomplete,
  MyAvatar,
  MyBacktop,
  MyBadge,
  MyBreadcrumb,
  MyBreadcrumbItem,
  MyButton,
  MyCalendar,
  MyCard,
  MyCarousel,
  MyCarouselItem,
  MyCascader,
  MyCheckbox,
  MyCheckboxGroup,
  MyCol,
  MyCollapse,
  MyCollapseItem,
  MyColorPicker,
  MyColorPickerPanel,
  MyConfigProvider,
  MyContainer,
  MyDatePicker,
  MyDatePickerPanel,
  MyDateTimePicker,
  MyDescriptions,
  MyDescriptionsItem,
  MyDialog,
  MyDivider,
  MyDrawer,
  MyDropdown,
  MyDropdownItem,
  MyEmpty,
  MyFooter,
  MyForm,
  MyFormItem,
  MyHeader,
  MyIcon,
  MyImage,
  MyInfiniteScroll,
  MyInput,
  MyInputNumber,
  MyInputOtp,
  MyInputTag,
  MyLink,
  MyMain,
  MyMention,
  MyMenu,
  MyMenuItem,
  MyOption,
  MyPageHeader,
  MyPagination,
  MyParagraph,
  MyPopconfirm,
  MyPopover,
  MyProgress,
  MyRadio,
  MyRadioGroup,
  MyRate,
  MyResult,
  MyRow,
  MyScrollbar,
  MySegmented,
  MySelect,
  MySkeleton,
  MySlider,
  MySpace,
  MySplitter,
  MyStatistic,
  MyStep,
  MySteps,
  MySubMenu,
  MySwitch,
  MyTabPane,
  MyTable,
  MyTableColumn,
  MyTabs,
  MyTag,
  MyText,
  MyTimePicker,
  MyTimeSelect,
  MyTimeline,
  MyTimelineItem,
  MyTitle,
  MyTooltip,
  MyTour,
  MyTransfer,
  MyTree,
  MyTreeSelect,
  MyUpload,
  MyVirtualList,
  MyVirtualizedSelect,
  MyVirtualizedTable,
  MyVirtualizedTree,
  MyWatermark,
} from '../components'
import { MyLoading, vLoading } from '../components/loading'
import { installMessage } from '../components/message'
import { installMessageBox } from '../components/message-box'
import { installNotification, Notification } from '../components/notification'
import { applyTheme, createTheme, defaultThemeInput, type ThemeInput } from '../hooks'
import '../theme-chalk/src/index.scss'

export interface MyUIOptions {
  theme?: ThemeInput
}

const components = [
  MyAffix,
  MyAlert,
  MyAnchor,
  MyAside,
  MyAutocomplete,
  MyAvatar,
  MyBacktop,
  MyBadge,
  MyBreadcrumb,
  MyBreadcrumbItem,
  MyButton,
  MyCalendar,
  MyCard,
  MyCarousel,
  MyCarouselItem,
  MyCascader,
  MyCheckbox,
  MyCheckboxGroup,
  MyCol,
  MyCollapse,
  MyCollapseItem,
  MyColorPicker,
  MyColorPickerPanel,
  MyConfigProvider,
  MyContainer,
  MyDatePicker,
  MyDatePickerPanel,
  MyDateTimePicker,
  MyDescriptions,
  MyDescriptionsItem,
  MyDialog,
  MyDivider,
  MyDrawer,
  MyDropdown,
  MyDropdownItem,
  MyEmpty,
  MyFooter,
  MyForm,
  MyFormItem,
  MyHeader,
  MyIcon,
  MyImage,
  MyInfiniteScroll,
  MyInput,
  MyInputNumber,
  MyInputOtp,
  MyInputTag,
  MyLink,
  MyMain,
  MyMention,
  MyMenu,
  MyMenuItem,
  MyOption,
  MyPageHeader,
  MyPagination,
  MyParagraph,
  MyPopconfirm,
  MyPopover,
  MyProgress,
  MyRadio,
  MyRadioGroup,
  MyRate,
  MyResult,
  MyRow,
  MyScrollbar,
  MySegmented,
  MySelect,
  MySkeleton,
  MySlider,
  MySpace,
  MySplitter,
  MyStatistic,
  MyStep,
  MySteps,
  MySubMenu,
  MySwitch,
  MyTabPane,
  MyTable,
  MyTableColumn,
  MyTabs,
  MyTag,
  MyText,
  MyTimePicker,
  MyTimeSelect,
  MyTimeline,
  MyTimelineItem,
  MyTitle,
  MyTooltip,
  MyTour,
  MyTransfer,
  MyTree,
  MyTreeSelect,
  MyUpload,
  MyVirtualList,
  MyVirtualizedSelect,
  MyVirtualizedTable,
  MyVirtualizedTree,
  MyWatermark,
] as const

const MyUI: Plugin<[MyUIOptions?]> = {
  install(app: App, options: MyUIOptions = {}) {
    components.forEach((component) => {
      app.use(component)
    })

    app.directive('loading', vLoading)
    installMessage(app)
    installMessageBox(app)
    installNotification(app)
    app.config.globalProperties.$notification = Notification
    app.config.globalProperties.$loading = MyLoading

    applyTheme(createTheme(options.theme ?? defaultThemeInput))
  },
}

export * from '../components'
export * from '../hooks'
export * from '../locale'
export default MyUI
